---
- name: Deploy sample application to OpenShift
  hosts: all
  tasks:
    - name: Create a Openshift namespace
     redhat.openshift.k8s:
       name: sbi_demo
       api_version: v1
       kind: Namespace
       state: present
     delegate_to: localhost

    - name: Create deployment
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: sample-deployment
            namespace: sbi_demo
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: sample-app
            template:
              metadata:
                labels:
                  app: sample-app
              spec:
                containers:
                - name: sample-container
                  image: nginx:latest
                  ports:
                  - containerPort: 80

    - name: Create service
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: sample-service
            namespace: sbi_demo
          spec:
            selector:
              app: sample-app
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create route
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Route
          metadata:
            name: sample-route
            namespace: sbi_demo
          spec:
            to:
              kind: Service
              name: sample-service
            port:
              targetPort: 80
            tls:
              termination: edge
